services:
  chatserver:
    build:
      context: ./chatserver
      dockerfile: dockerfile
    networks:
      - app_network
    ports:
      - "8080:8080"
    env_file: ".env.dev"
      

networks:
  app_network:
    driver: bridge
